### ISSUE TITLE
This implementation is incorrect and insecure

### ISSUE THREAD

**Issue by psibean** [doochik/express-csrf-double-submit-cookie#20]
Firstly, this method default partially copied from csurf is one of the reasons it is insecure, you NEED to override this and this should be made extremely clear:

```js
function defaultValue (req) {
    return (req.body && req.body._csrf_token) ||
        (req.query && req.query._csrf_token) ||
        (req.headers['x-csrf-token']);
}
```

If the user of this package is trying to use the header, but an attacker puts something in the body, it's going to check and use that first.

Secondly, you should be hashing or at least signing the cookie - ideally do both.

**Comment by doochik** [comment]
Fix prioritization at #21. Thanks!

Token is generated by [crypto.randomBytes](https://nodejs.org/dist/latest-v18.x/docs/api/crypto.html#cryptorandombytessize-callback) (`Generates cryptographically strong pseudorandom data`) already. Hashing is not necessary cause it doesn't bring more entropy. 
Also you can sign cookie at your app with `cookie` options.
